package api

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Homebase's own certificate.
//
// A home server has no public name and no way to get a certificate anybody
// already trusts: Let's Encrypt needs a domain and an internet-facing machine,
// and Homebase deliberately has neither. So it signs its own, and the user
// trusts it once.
//
// That is a real cost and it is not hidden: the browser will warn the first
// time, and being taught to click through security warnings is its own harm. It
// is paid because the alternative is a password crossing a network the threat
// model describes as containing a smart television with unpatched firmware. The
// mitigation is that the machine prints its own fingerprint on its own screen,
// so the warning becomes something to check rather than something to dismiss.
//
// Generated by core rather than by hostd. Nothing here needs privilege — the
// key lives in core's own state directory and the port is above 1024 — and
// ADR-0006 is about keeping privileged surface small, not about routing
// everything through it.

const (
	// Long-lived on purpose. This is trust on first use: the user accepts this
	// certificate once, and every renewal would ask them to do it again, which
	// is how "check the fingerprint" degrades into "click through the warning".
	certLifetime = 10 * 365 * 24 * time.Hour

	certFile = "tls/homebase.crt"
	keyFile  = "tls/homebase.key"
)

// Identity is the certificate core serves, and the fingerprint a user checks.
type Identity struct {
	CertPath string
	KeyPath  string

	// Fingerprint is the SHA-256 of the certificate, formatted the way browsers
	// show it. This is the string printed on the machine's own screen.
	Fingerprint string

	// Names is everything the certificate is valid for, for the same screen.
	Names []string
}

// EnsureCertificate returns the server's certificate, creating one if there is
// none or if the names it covers no longer match this machine.
//
// `names` are the DNS names it must cover — the hostname and its `.local` form.
// Addresses are discovered here, because they are a property of the machine
// rather than a decision anybody makes.
func EnsureCertificate(stateDir string, names []string) (*Identity, error) {
	certPath := filepath.Join(stateDir, certFile)
	keyPath := filepath.Join(stateDir, keyFile)

	wanted := certificateNames(names)

	if existing, err := loadIdentity(certPath, keyPath, wanted); err == nil {
		return existing, nil
	}

	if err := os.MkdirAll(filepath.Dir(certPath), 0o700); err != nil {
		return nil, fmt.Errorf("creating the certificate directory: %w", err)
	}

	identity, err := generate(certPath, keyPath, wanted)
	if err != nil {
		return nil, err
	}
	return identity, nil
}

// loadIdentity returns the stored certificate if it is still usable.
//
// "Usable" means it parses, has not expired, and still covers the names this
// machine answers to. A certificate that no longer matches is replaced rather
// than served: a name mismatch produces the same browser warning as a missing
// certificate, with none of the reassurance.
func loadIdentity(certPath, keyPath string, wanted certNames) (*Identity, error) {
	block, err := os.ReadFile(certPath)
	if err != nil {
		return nil, err
	}
	if _, err := os.Stat(keyPath); err != nil {
		return nil, err
	}

	decoded, _ := pem.Decode(block)
	if decoded == nil {
		return nil, fmt.Errorf("the stored certificate is not PEM")
	}
	parsed, err := x509.ParseCertificate(decoded.Bytes)
	if err != nil {
		return nil, err
	}

	if time.Now().After(parsed.NotAfter) {
		return nil, fmt.Errorf("the stored certificate has expired")
	}
	if !covers(parsed, wanted) {
		return nil, fmt.Errorf("the stored certificate does not cover this machine's names")
	}

	return &Identity{
		CertPath:    certPath,
		KeyPath:     keyPath,
		Fingerprint: fingerprint(parsed.Raw),
		Names:       wanted.display(),
	}, nil
}

func covers(cert *x509.Certificate, wanted certNames) bool {
	have := make(map[string]bool, len(cert.DNSNames))
	for _, name := range cert.DNSNames {
		have[strings.ToLower(name)] = true
	}
	for _, name := range wanted.dns {
		if !have[strings.ToLower(name)] {
			return false
		}
	}

	// Addresses deliberately do not invalidate a certificate.
	//
	// DHCP hands out a different address on a different network, and
	// regenerating for that would change the fingerprint the user checked and
	// ask them to trust the machine again — routinely, and for a reason they
	// have no way to distinguish from an attack. The names are the stable
	// identity; addresses are a convenience for reaching it before mDNS works.
	return true
}

func generate(certPath, keyPath string, wanted certNames) (*Identity, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("generating a key: %w", err)
	}

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, fmt.Errorf("generating a serial number: %w", err)
	}

	subject := "Homebase"
	if len(wanted.dns) > 0 {
		subject = wanted.dns[0]
	}

	template := x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			CommonName:   subject,
			Organization: []string{"Homebase"},
		},
		NotBefore: time.Now().Add(-time.Hour),
		NotAfter:  time.Now().Add(certLifetime),

		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		// Self-signed and therefore its own issuer. Marked as a CA because some
		// platforms will not let a user trust a leaf certificate directly, and a
		// certificate somebody cannot choose to trust defeats the whole design.
		IsCA: true,

		DNSNames:    wanted.dns,
		IPAddresses: wanted.ips,
	}

	der, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		return nil, fmt.Errorf("creating the certificate: %w", err)
	}

	if err := writePEM(certPath, "CERTIFICATE", der, 0o644); err != nil {
		return nil, err
	}

	encodedKey, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return nil, fmt.Errorf("encoding the key: %w", err)
	}
	// 0600: the private key is the one file here that must not be readable by
	// anything else on the machine, including the applications Homebase runs.
	if err := writePEM(keyPath, "EC PRIVATE KEY", encodedKey, 0o600); err != nil {
		return nil, err
	}

	return &Identity{
		CertPath:    certPath,
		KeyPath:     keyPath,
		Fingerprint: fingerprint(der),
		Names:       wanted.display(),
	}, nil
}

func writePEM(path, blockType string, der []byte, mode os.FileMode) error {
	// Written to a temporary file and renamed, so a machine that loses power
	// here comes back with either the old pair or the new one, never half a
	// certificate that core then refuses to start with.
	temporary := path + ".new"
	file, err := os.OpenFile(temporary, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, mode)
	if err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	if err := pem.Encode(file, &pem.Block{Type: blockType, Bytes: der}); err != nil {
		_ = file.Close()
		return fmt.Errorf("writing %s: %w", path, err)
	}
	if err := file.Sync(); err != nil {
		_ = file.Close()
		return fmt.Errorf("writing %s: %w", path, err)
	}
	if err := file.Close(); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return os.Rename(temporary, path)
}

// fingerprint formats a SHA-256 the way browsers show it, so the string on the
// machine's screen can be compared to the one in the browser character by
// character without the user having to interpret anything.
func fingerprint(der []byte) string {
	sum := sha256.Sum256(der)
	parts := make([]string, len(sum))
	for i, b := range sum {
		parts[i] = fmt.Sprintf("%02X", b)
	}
	return strings.Join(parts, ":")
}

type certNames struct {
	dns []string
	ips []net.IP
}

func (n certNames) display() []string {
	out := append([]string{}, n.dns...)
	for _, ip := range n.ips {
		out = append(out, ip.String())
	}
	return out
}

// certificateNames works out everything the certificate should be valid for.
func certificateNames(names []string) certNames {
	seen := map[string]bool{}
	var dns []string

	add := func(name string) {
		name = strings.TrimSpace(strings.ToLower(name))
		if name == "" || seen[name] {
			return
		}
		seen[name] = true
		dns = append(dns, name)
	}

	for _, name := range names {
		add(name)
	}
	add("localhost")

	ips := localAddresses()
	return certNames{dns: dns, ips: ips}
}

// localAddresses returns the addresses this machine currently answers on.
//
// Included so that a user who reaches the server by address — before mDNS
// works, or on a network where it does not — gets a certificate that matches
// rather than a second, different-looking warning.
func localAddresses() []net.IP {
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback}
	}

	var ips []net.IP
	seen := map[string]bool{}
	for _, addr := range addrs {
		network, ok := addr.(*net.IPNet)
		if !ok {
			continue
		}
		if network.IP.IsLinkLocalUnicast() || network.IP.IsLinkLocalMulticast() {
			continue
		}
		if seen[network.IP.String()] {
			continue
		}
		seen[network.IP.String()] = true
		ips = append(ips, network.IP)
	}

	sort.Slice(ips, func(i, j int) bool { return ips[i].String() < ips[j].String() })
	return ips
}

// RedirectToTLS answers the plain port with a redirect to the encrypted one.
//
// Not a proxy and not a second copy of the dashboard: everything on the plain
// port is answered with "go there instead", so there is exactly one origin the
// dashboard is ever served from. Two would mean two sets of cookies and a
// session that appears to vanish when somebody follows a link on the wrong one.
//
// The host is taken from the request, so whatever name the user reached the
// machine by — `homebase.local`, a bare hostname, an address — is the name they
// keep. Redirecting to a name the server prefers is how somebody who typed an
// address ends up at a name their network cannot resolve.
func RedirectToTLS(tlsAddr string) http.Handler {
	_, port, err := net.SplitHostPort(tlsAddr)
	if err != nil {
		port = "8443"
	}

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		host := r.Host
		if h, _, err := net.SplitHostPort(host); err == nil {
			host = h
		}
		if host == "" {
			http.Error(w, "Homebase is served over HTTPS.", http.StatusBadRequest)
			return
		}

		target := "https://" + net.JoinHostPort(host, port) + r.URL.RequestURI()

		// 307 rather than 301: permanent redirects are cached by browsers
		// indefinitely, and a machine that later serves plain HTTP again — a
		// downgrade during recovery, say — would be unreachable from every
		// browser that had ever seen the old answer.
		http.Redirect(w, r, target, http.StatusTemporaryRedirect)
	})
}
