import { type ReactNode } from "react";

/**
 * Just enough Markdown to read a model's answer.
 *
 * The model writes Markdown whether or not anybody asked it to — headings,
 * `**bold**`, bulleted lists — and rendering that as literal text is how an
 * answer ends up reading as `### **Home lab** — experiment with Docker`. Asking
 * it in a prompt to stop is not reliable; rendering what it actually produces
 * is.
 *
 * **Elements, never HTML.** Nothing here goes near `dangerouslySetInnerHTML`.
 * This text is generated by a model that will happily repeat whatever a person
 * pasted into it, so it is treated exactly like any other untrusted string: it
 * becomes React children, and a `<script>` in the output is a `<script>` on the
 * screen as characters.
 *
 * A deliberate subset — headings, lists, code, bold, italic, links are *not*
 * included. This is for reading a paragraph, not for typesetting a document,
 * and every construct supported is one more thing to get wrong while the text
 * is still arriving half-finished.
 *
 * Which is the other constraint: this renders **partial** input. A sentence
 * mid-stream ends inside a `**` about a third of the time, so unterminated
 * markers have to render as the plain text they currently are rather than
 * swallowing the rest of the answer.
 */

/** Inline markers: `code`, **bold**, *italic*. */
function inline(text: string, keyPrefix: string): ReactNode[] {
  const out: ReactNode[] = [];
  let rest = text;
  let index = 0;

  // Ordered longest-marker-first so ** is never mistaken for two *.
  const patterns: { open: string; close: string; wrap: (child: string, key: string) => ReactNode }[] = [
    { open: "`", close: "`", wrap: (child, key) => <code key={key}>{child}</code> },
    { open: "**", close: "**", wrap: (child, key) => <strong key={key}>{child}</strong> },
    { open: "*", close: "*", wrap: (child, key) => <em key={key}>{child}</em> },
  ];

  while (rest.length > 0) {
    let best: { at: number; pattern: (typeof patterns)[number]; end: number } | null = null;

    for (const pattern of patterns) {
      const at = rest.indexOf(pattern.open);
      if (at === -1) continue;
      const end = rest.indexOf(pattern.close, at + pattern.open.length);
      // No closing marker yet: the text is still arriving, so this is not
      // emphasis, it is a literal asterisk somebody is about to finish typing.
      if (end === -1) continue;
      // Empty spans (`**` on its own) are not emphasis either.
      if (end === at + pattern.open.length) continue;
      if (best === null || at < best.at) best = { at, pattern, end };
    }

    if (best === null) {
      out.push(rest);
      break;
    }

    if (best.at > 0) out.push(rest.slice(0, best.at));
    const inner = rest.slice(best.at + best.pattern.open.length, best.end);
    out.push(best.pattern.wrap(inner, `${keyPrefix}-${index++}`));
    rest = rest.slice(best.end + best.pattern.close.length);
  }

  return out;
}

export function Markdown({ text }: { text: string }) {
  const blocks: ReactNode[] = [];
  const lines = text.split("\n");

  let listItems: ReactNode[] = [];
  let ordered = false;
  let codeLines: string[] | null = null;

  const flushList = () => {
    if (listItems.length === 0) return;
    const items = listItems;
    listItems = [];
    blocks.push(
      ordered ? (
        <ol key={`b${blocks.length}`}>{items}</ol>
      ) : (
        <ul key={`b${blocks.length}`}>{items}</ul>
      ),
    );
  };

  for (const [number, line] of lines.entries()) {
    // Fenced code. An unclosed fence at the end of a stream still renders as a
    // code block, which is what it is going to become.
    if (line.trimStart().startsWith("```")) {
      if (codeLines === null) {
        flushList();
        codeLines = [];
      } else {
        blocks.push(<pre key={`b${blocks.length}`}>{codeLines.join("\n")}</pre>);
        codeLines = null;
      }
      continue;
    }
    if (codeLines !== null) {
      codeLines.push(line);
      continue;
    }

    // A rule. Models use these to separate sections and they appear often
    // enough that leaving them as literal "---" is visible in almost every
    // long answer.
    if (/^\s*([-*_])\s*(\1\s*){2,}$/.test(line)) {
      flushList();
      blocks.push(<hr key={`b${blocks.length}`} />);
      continue;
    }

    const heading = /^(#{1,6})\s+(.*)$/.exec(line);
    if (heading) {
      flushList();
      // Rendered as one size regardless of depth. A model's "###" carries no
      // reliable information about level, and six sizes of heading inside a
      // chat reply is noise pretending to be structure.
      blocks.push(
        <p className="assistant-heading" key={`b${blocks.length}`}>
          {inline(heading[2] ?? "", `h${number}`)}
        </p>,
      );
      continue;
    }

    const bullet = /^\s*[-*+]\s+(.*)$/.exec(line);
    const numbered = /^\s*\d+[.)]\s+(.*)$/.exec(line);
    if (bullet || numbered) {
      const nowOrdered = numbered !== null;
      // A list that changes kind part-way is two lists, so the first is closed
      // while `ordered` still says what it was.
      if (listItems.length > 0 && ordered !== nowOrdered) {
        flushList();
      }
      ordered = nowOrdered;
      listItems.push(
        <li key={`i${number}`}>{inline((bullet ?? numbered)?.[1] ?? "", `l${number}`)}</li>,
      );
      continue;
    }

    flushList();
    if (line.trim() === "") continue;
    blocks.push(<p key={`b${blocks.length}`}>{inline(line, `p${number}`)}</p>);
  }

  flushList();
  if (codeLines !== null && codeLines.length > 0) {
    blocks.push(<pre key={`b${blocks.length}`}>{codeLines.join("\n")}</pre>);
  }

  return <>{blocks}</>;
}
